### deposit
POST  http://localhost:3000/api/v1/deposit
Content-Type: application/json
  
{
  "amount": 9000000
}

### deposit
POST  https://tabungankuu.up.railway.app/api/v1/withdraw
Content-Type: application/json
  
{
  "amount": 12000
}

### all history
GET  http://localhost:3000/api/v1/history
Content-Type: application/json

### history deposit
GET  http://localhost:3000/api/v1/history/deposit
Content-Type: application/json

### history withdraw
GET  http://localhost:3000/api/v1/history/withdrawal
Content-Type: application/json

### withdraw all
POST http://localhost:3000/api/v1/withdraw-all
Content-Type: application/json
